package org.rainbow.silence_kingdom.view;

import org.rainbow.silence_kingdom.conts.ViewType;
import org.rainbow.silence_kingdom.util.Meta;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;

/**
 * Copyright (c) by Megvii.com.
 * Created by Rainbow Sun.
 * Date: 2017/10/21.
 * Time: 下午2:32.
 * Description:
 */
public class PreStartView extends BaseView {

    private static final Logger logger = LoggerFactory.getLogger(PreStartView.class);
    private JPanel panel;

    protected PreStartView(BaseFrame baseFrame) {
        super(baseFrame);
        $$$setupUI$$$();
        new Thread(new Runnable() {
            @Override public void run() {
                try {
                    Thread.sleep(3000);
                    logger.info("switch");
                    baseFrame.viewSwitch(new AudioRecordView(baseFrame));
                } catch (InterruptedException e) {
                    logger.error("sleep failed");
                }
            }
        }).start();
    }

    @Override ViewType getViewType() {
        return null;
    }

    @Override Container getView() {
        return panel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        panel = new JPanel() {
            @Override protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(Meta.IMG_DIR.getAbsolutePath() + "/pre_start.jpg");
                Image img = icon.getImage();
                g.drawImage(img, 0, 0, icon.getIconWidth(),
                        icon.getIconHeight(), icon.getImageObserver());
            }
        };
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
